(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "pallet")
(depends-on "use-package")
(depends-on "yasnippet")
(depends-on "init-loader")

(depends-on "haml-mode")
(depends-on "scss-mode")
(depends-on "haskell-mode")
(depends-on "go-mode")
(depends-on "coffee-mode")
(depends-on "markdown-mode")
(depends-on "cuda-mode")
